### ISSUE TITLE
Move to ES6?

### ISSUE THREAD

**Issue by estliberitas** [freeall/redis-eventemitter#9]
@freeall just wanted to ask if you're OK with me working on this? Actually, currently implementation is not so optimized. So I would refactor it and optimize as possible.

**Comment by freeall** [comment]
Optimize is good, but we can't move to ES6 as it's a module and others depend on it

**Comment by estliberitas** [comment]
@freeall what do you mean by "as it's a module and others depending on it"? It's to be different version, probably major one and with `npm publish` you can actually enforce people continue install current major version instead of a newer one (if you want to). Plus, I can make it compatible with current API. Just change of syntax and some of the structures for optimization purposes. So, it's refactoring and not re-design.

**Comment by freeall** [comment]
If the ones who use it uses an older version of node it won't work. So unless there's a really good reason for it, I don't see why we should break the module for someone

**Comment by estliberitas** [comment]
@freeall how will we break it, man? How? If it's a major version neither `~a.b.c` nor `^a.b.c` version specifications lead to installation of newer version.

**Comment by freeall** [comment]
If someone uses an older version of node they will not be able to use this module. Of course they can use the current (which would then be the older) version, but they can't use the new one.

So now you should argue why you think it should move to ES6? Is it faster or can it do something you can't now?

**Comment by estliberitas** [comment]
@freeall argument is simple - node moves toward es6, so follow the trend. that's all. :-)

**Comment by freeall** [comment]
@estliberitas Maybe, but it will make the module unusable for those with older versions. We shouldn't do that.

ES6 is fine for apps, but not for modules as they may be used in a non-ES6 context. So for now modules should generally not be written in ES6 - unless there is a good reason for it of course.

**Comment by markjrodrigues** [comment]
@estliberitas Did you end up forking a new version of this which is optimised for ES6? I would prefer to use that if it is actively being developed.

**Comment by freeall** [comment]
@markjrodrigues Mostly not active because there haven't been anything new to add to the module. If something isn't working you can always open an issue and we'll look at it. And pr's always welcome :)

**Comment by estliberitas** [comment]
@markjrodrigues nope. I actually would like to do that and use `ioredis` instead of `redis`.

**Comment by estliberitas** [comment]
Basically that is already done: https://github.com/ziyasal/ioredis-eventemitter

**Comment by freeall** [comment]
@estliberitas what's the difference between `ioredis` and `redis`? I was using this module again the other day, but when I updated `redis` to the newest version I couldn't get it to work (didn't look that much into it though)
